# Generated by Django 5.0 on 2023-12-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesr',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
